=== ErikPC/Apuntes_importantes/activiadades xml/Actividad_entregable_1/act_1/productes.dtd
<!ELEMENT productes (producte+)>
<!ELEMENT producte (ratoli?,teclat?,monitor?)>
<!ELEMENT ratoli (#PCDATA)>
<!ELEMENT teclat (#PCDATA)>
<!ELEMENT monitor (#PCDATA)>
<!ATTLIST ratoli codi NMTOKEN #REQUIRED>
<!ATTLIST teclat codi NMTOKEN #REQUIRED>
<!ATTLIST monitor codi NMTOKEN #REQUIRED>

=== ErikPC/Apuntes_importantes/activiadades xml/Actividad_entregable_1/act_1/productes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE productes SYSTEM "productes.dtd">
<productes>
    <producte>
        <ratoli codi="r01"> sense fil space </ratoli>
    </producte>
    <producte>
        <teclat codi="t03">Teclat de colors </teclat>
    </producte>
    <producte>
        <teclat codi="t04">Teclat de colors </teclat>
        <monitor codi="m100">TÃ ctil</monitor>
    </producte>
</productes>
